variable "docker_image_tag" {}
variable "github_docker_registry_url" {}
variable "github_token" {}
variable "kubernetes_api_server_endpoint" {}
variable "kubernetes_api_server_cert_auth" {}
variable "mysql_username" {}
variable "mysql_password" {}
variable "provider_access_key" {}
variable "provider_secret_key" {}
variable "ssl_cert_arn" {}
